# Generated by Django 3.2.8 on 2022-01-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220125_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='boss_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
    ]
