# Generated by Django 3.2.8 on 2022-01-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_boss_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
