# Generated by Django 3.2.8 on 2022-01-26 18:17

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManger()),
            ],
        ),
    ]
