# Generated by Django 3.2.8 on 2022-01-27 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='boss_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
