# Generated by Django 3.2.8 on 2022-01-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220127_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='path',
            new_name='hours_of_work',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='boss_id',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='center',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='radius',
        ),
        migrations.AddField(
            model_name='activity',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.company'),
        ),
        migrations.AddField(
            model_name='activity',
            name='num_out_of_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sales_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
