# Generated by Django 3.2.8 on 2022-02-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220127_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='center',
            new_name='center_x',
        ),
        migrations.AddField(
            model_name='customuser',
            name='center_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
