# Generated by Django 3.2.8 on 2022-01-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220127_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
