# Generated by Django 3.2.8 on 2022-01-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='company_id',
            new_name='company',
        ),
    ]
