# Generated by Django 3.2.8 on 2022-01-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_company_id_product_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
